x = "hello World"  # str
x = 20  # int
x = 20.5  # float
x = ["apple", "banana", "cherry"]  # list
x = ("apple", "banana", "cherry")  # tuple
x = {"name": "kanpicha", "age": 21}  # dict
x = frozenset({"apple", "banana", "cherry"})  # frozenset
x = True  # bool
x = b"hello"  # bytes
